/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package cn.thrift.demo.helloworld;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class HelloConstants {

  public static final java.lang.String VERSION = "1.0.1";

}
